# Generated by Django 4.2.18 on 2025-01-24 15:12

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved',
            new_name='reported',
        ),
        migrations.AddField(
            model_name='post',
            name='dream_or_nightmare',
            field=models.CharField(choices=[('dream', 'Dream'), ('nightmare', 'Nightmare')], default='dream', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='reoccurring',
            field=models.BooleanField(choices=[(True, 'Reoccuring'), (False, 'Not Reoccurring')], default=False),
        ),
    ]
