# Generated by Django 4.2.18 on 2025-01-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_comment_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reoccurring',
            field=models.BooleanField(choices=[(True, 'Reoccurring'), (False, 'Not Reoccurring')], default=False),
        ),
    ]
